Fix generated enum unmarshalling
discord-gophers/goapi-gen pull request #72
Opened 2022-01-04 02:42 UTC by dustin-decker

Fixes two issues:

- UnmarshalJSON never updated the internal value after unmarshaling.
- Methods must have a pointer receiver for updates to take effect.

2022-01-04 14:26 UTC, hhhapz commented
Can you please run all of the tests and add all of the changed templates (generated or not) so that the checks can pass? Thanks!

2022-01-04 14:55 UTC, zacharyburkett requested changes
Checks are not passing

2022-01-04 19:44 UTC, dustin-decker commented
I ran `go generate ./...` to update the generated schema. All tests seem to be passing already.

2022-01-13 13:23 UTC, Karitham approved these changes

2022-01-20 13:02 UTC, zacharyburkett approved these changes

2022-01-20 13:03 UTC, merged